name: Publish website

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  publish_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - name: Install Python dependencies
        run: |
          pip install sphinx sphinx-book-theme
      - name: Sphinx build
        run: |
          sphinx-build website/src build
      - name: Deploy Sphinx website to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/
          force_orphan: true
